export default function Disclaimer() {
  return (
    <div className="panel p-3 sm:p-4 mt-4 border-yellow-900 bg-[#0d0d00]">
      <div className="text-yellow-600 text-[10px] sm:text-xs leading-relaxed">
        <strong className="text-yellow-500">DISCLAIMER:</strong> This dashboard is for internal agentic desk context only. 
        The content displayed represents hypothetical trading theses generated by automated quant systems. 
        This is <strong>NOT</strong> investment advice, and no real trades or positions are represented. 
        Do not rely on any information shown here for actual trading decisions. 
        Past performance of any strategy, whether real or hypothetical, is not indicative of future results.
      </div>
    </div>
  )
}
