export default function Disclaimer() {
  return (
    <div className="rounded-panel border border-desk-draft/20 bg-desk-draft/[0.03] p-4 sm:p-5">
      <div className="eyebrow text-desk-draft/80">Disclaimer</div>
      <p className="mt-2.5 text-[12.5px] leading-relaxed text-desk-muted sm:text-[13px]">
        This dashboard is for internal agentic desk context only. The content
        shown represents hypothetical trading theses generated by automated quant
        systems. This is <strong className="font-semibold text-desk-dim">not</strong>{' '}
        investment advice, and no real trades or positions are represented. Do not
        rely on anything here for actual trading decisions. Past performance of
        any strategy, real or hypothetical, is not indicative of future results.
      </p>
    </div>
  )
}
